project:
  type: book

book:
  title: "Computational Text Analysis "
  subtitle: "Jour 389R/689R |Fall 2024, Philip Merrill College of Journalism"
  author: 
    - name: "Rob Wells"
    - name: "Sean Mussenden"
    - name: "Derek Willis"
    - name: "Matt Waite"
    - name: "Sarah Cohen"
  date: "8/26/2024"
  chapters:
     - index.qmd
     - start-story.qmd
     - start-math.qmd
     - xl-intro.qmd
     - xl-refresher.qmd
     - xl-filter-sort.qmd
     - xl-formulas.qmd
     - xl-pivot.qmd
     - xl-sheets_cleaning.qmd
     - r-start.qmd
     - r-load-analyze-visualize.qmd
     - github.qmd
     - r_aggregates_filters.qmd
     - r-mutating.qmd
     - r-join-bind.qmd
     - r-data-cleaning.qmd
     - r-publication.qmd
     - r-writing-data.qmd
     - appendix-math.qmd

  #  - aggregates.qmd
  #  - mutating.qmd
  #  - workingwithdates.qmd
  #  - filters.qmd
  #  - datacleaning-part-i.qmd
  #  - datacleaning-part-ii.qmd
  #  - open-refine.qmd
  #  - pdfs.qmd
  #  - merging.qmd

format:
  html:
    theme: simplex
  #pdf:
  #  documentclass: scrreprt
 # epub:
 #    cover-image: cover.png

editor: visual

execute:
  cache: false